site_name: hhaliloff
theme: simple-blog

nav:
    - ГЛАВНАЯ: index.md
    - О СЕБЕ: about_me.md
    - ПРОЕКТЫ:
        - ОБЗОР: overview.md
        - Проект 1: currency-tracker.md
        - Проект 2: notes.md
        - Проект 3: optimization.md